language: node_js

node_js:
  - '10'

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libsecret-1-dev

before_script:
  - npm install
  - export NODE_OPTIONS=–max_old_space_size=16384

script:
  - npm run lint
  - CI= npm run test:ci

after_success:
  - codecov --token="$CODECOV_TOKEN"

branches:
  except:
  - /^v\d+\.\d+\.\d+$/
  only:
  - main
  - /v\d-beta/
