language: node_js

node_js:
  - '8'

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libsecret-1-dev

before_script:
  - npm install

script:
  - npm run lint
  - npm run test

branches:
  except:
  - /^v\d+\.\d+\.\d+$/
  only:
  - master
  - dev
