version: 2.1

parameters:
  run_e2e_test:
    default: false
    type: boolean
  run_pr_validator:
    default: true
    type: boolean
  package_version:
    default: ''
    type: string

executors:
  node:
    parameters:
      tag:
        type: string
    docker:
      - image: cimg/node:<< parameters.tag >>

orbs:
  win: circleci/windows@2.2.0

commands:
  install-dependencies:
    steps:
      - run:
          name: "Install project dependencies"
          command: npm i
  install-prerequisites:
    steps:
      - run:
          name: "APT update"
          command: sudo apt-get update
      - run:
          name: "Fetch and install libsecret"
          command: sudo apt-get install -y libsecret-1-dev
  run-unit-tests:
    steps:
      - run:
          name: "Run unit tests"
          command: npm run test:ci
  run-linter:
    steps:
      - run:
          name: "Run linter"
          command: npm run lint
  run-e2e-tests:
    steps:
      - run:
          name: "Run e2e tests"
          command: cd packages/flex-plugin-e2e-tests && npm run build && npm start

jobs:
  job_e2e-test:
    resource_class: xlarge
    parameters:
      package_version:
        type: string
    environment:
      PACKAGE_VERSION: << parameters.package_version >>
      NODE_VERSION: "lts"
    executor:
      name: node
      tag: "lts"
    steps:
      - checkout
      - install-prerequisites
      - install-dependencies
      - run-e2e-tests

  job_pr-validator-win32:
    environment:
      NODE_OPTIONS: --max-old-space-size=14336
      CI: ""
    parameters:
      shell:
        type: string
    executor:
      name: win/default
      shell: << parameters.shell >>
    steps:
      - checkout
      - install-prerequisites
      - install-dependencies
      - run-linter
      - run-unit-tests

  job_pr-validator-node:
    resource_class: xlarge
    environment:
      NODE_OPTIONS: --max-old-space-size=14336
      CI: ""
    parameters:
      node-version:
        type: string
    executor:
      name: node
      tag: << parameters.node-version >>
    steps:
      - checkout
      - install-prerequisites
      - install-dependencies
      - run-linter
      - run-unit-tests
      - when:
          condition:
            equal: [<< parameters.node-version >>, lts]
          steps:
            - run:
                name: "CODECOV"
                command: npm run coverage -- --token=$CODECOV_TOKEN

workflows:
  test:
    when: << pipeline.parameters.run_e2e_test >>
    jobs:
      - job_e2e-test:
          matrix:
            parameters:
              package_version: [ << pipeline.parameters.package_version >> ]
  validate:
    when: << pipeline.parameters.run_pr_validator >>
    jobs:
      - job_pr-validator-win32:
          matrix:
            parameters:
                shell: [ "bash.exe" ]
      - job_pr-validator-node:
          matrix:
            parameters:
              node-version: ["10.24", "12.21", "14.16", lts]
          post-steps:
            - run:
                name: Send Slack notification
                command: |
                         curl -X POST -H "Content-type:application/json" --data "{'text':':error: $CIRCLE_PROJECT_REPONAME/$CIRCLE_BRANCH - $CIRCLE_PULL_REQUEST validation failed on *Node:${CIRCLE_JOB/job_pr-validator-node-/''}*. View <$CIRCLE_BUILD_URL|build>. cc: <@$CIRCLE_USERNAME>', 'mrkdwn':true}" $SLACK_WEBHOOK
                when: on_fail
